name: Build & Release

# Sets the trigger to changing the VERSION file in the main branch
on:
  push:
    branches:
    - main
    paths:
    - 'VERSION'

# Allows the workflow to create release
permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: windows-latest
    steps:
    - name: Sync Repo to the Server
      uses: actions/checkout@v1

    - name: Create Output Directory
      run: New-Item -ItemType Directory -Path .\output

    - name: Compile 64bit Binary
      run: gcc .\src\main.c -o .\output\unload_sysmon_x64.exe -s -m64 -lfltlib

    - name: Set up Go modules
      run: |
        if (!(Test-Path "go.mod")) {
          go mod init unload-sysmon
        }
        go get golang.org/x/sys/windows

    - name: Compile Go Binary
      run: |
        go build -ldflags="-s -w" -o .\output\unload_sysmon_go_x64.exe .\cmd\unload-sysmon\main.go

    - name: Read Version
      run: |
        $version = Get-Content VERSION
        Write-Output "VERSION=$version" >> $env:GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: ${{ github.event.repository.name }} ${{ env.VERSION }}
        make_latest: true
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        files: ./output/*
